--- /loadstring loadstring(Luacraft.httpGet("https://xdotsv.github.io/test.lua"))()
local player = LuaCraft.getLocalPlayer()
LuaCraftPlayer.player.giveItem("PISTON", 64)
LuaCraftPlayer.player.sendMessage("Lua code gave you a stack of pistons.")
local position = LuaCraftPlayer.player.getPosition()
LuaCraft.newEntity("FURNACE_MINECART", position)
LuaCraftPlayer.player.sendMessage("Spawned a furnace minecart at your current location.")
