--- /loadstring loadstring(Luacraft.httpGet("https://xdotsv.github.io/test.lua"))()
local player = LuaCraft.getLocalPlayer()
player.giveItem("PISTON", 64)
player.sendMessage("Lua code gave you a stack of pistons.")
local position = player.getPosition()
LuaCraft.newEntity("FURNACE_MINECART", position)
player.sendMessage("Spawned a furnace minecart at your current location.")
