--- /loadstring loadstring(Luacraft.httpGet("https://xdotsv.github.io/test.lua"))()
LuaCraftPlayer.name = LuaCraft.getLocalPlayer()
LuaCraft.player.giveItem("PISTON", 64)
LuaCraft.player.sendMessage("Lua code gave you a stack of pistons.")
local position = LuaCraftPlayer.player.getPosition()
LuaCraft.newEntity("FURNACE_MINECART", position)
LuaCraft.player.sendMessage("Spawned a furnace minecart at your current location.")
